resolver: lts-20.25
packages:
- sydtest
- sydtest-aeson
- sydtest-amqp
- sydtest-autodocodec
- sydtest-discover
- sydtest-hedgehog
- sydtest-hedis
- sydtest-hspec
- sydtest-mongo
- sydtest-persistent
- sydtest-persistent-postgresql
- sydtest-persistent-sqlite
- sydtest-process
- sydtest-rabbitmq
- sydtest-servant
- sydtest-typed-process
- sydtest-wai
- sydtest-webdriver
- sydtest-webdriver-screenshot
- sydtest-webdriver-yesod
- sydtest-yesod

- sydtest-misbehaved-test-suite

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages -O0

extra-deps:
- fast-myers-diff-0.0.0

system-ghc: true
nix:
  enable: false
with-hpack: hpack
