name: sydtest-persistent-postgresql
version: 0.2.0.3
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021-2022 Tom Sydney Kerckhove"
category: Testing
synopsis: An persistent-postgresql companion library for sydtest

extra-source-files:
- LICENSE.md
- CHANGELOG.md
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - monad-logger
  - mtl
  - persistent-postgresql
  - sydtest
  - sydtest-persistent
  - tmp-postgres

tests:
  sydtest-persistent-postgresql-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - persistent
    - sydtest
    - sydtest-persistent-postgresql
    when:
      - condition: flag(sydtest_integration_tests)
        then:
          buildable: True
        else:
          buildable: False

flags:
  sydtest_integration_tests:
    description: Whether to allow building integration tests
    manual: false
    default: true
