name: "Stack Build"
on:
  pull_request:
  push:
    branches: 
      - development
      - master

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: ["2.5.1"]
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v12
    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build dependencies
      run: |
        stack build   --system-ghc --no-nix --only-dependencies --test --bench --no-run-tests --no-run-benchmarks

    - name: Build autoexporter
      run: |
        stack install --system-ghc --no-nix autoexporter

    - name: Build
      run: |
        stack build   --system-ghc --no-nix --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test    --system-ghc --no-nix \
          --flag '*:-sydtest_integration_tests' # Don't run integration tests on CI because they would need rabbitmq-server and redis etc.
